chore (ci): Split unit test stage from build stage

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -130,8 +130,6 @@ jobs:
       if: matrix.platform == 'simulator'
       run: sudo apt update && sudo apt install libsdl2-dev --no-install-recommends -y
 
-    # Todo: run clang-tidy
-
     - name: Build binaries
       env:
         CACHED: ${{ steps.cache-build-tools.outputs.cache-hit }}
@@ -141,8 +139,43 @@ jobs:
         fi
         PATH="$PATH:$(pwd)/build-tools:$(pwd)/arm-gcc/bin"
         ./utilities/build.sh -f ${{ matrix.firmware }} -t ${{ matrix.target }} -p ${{ matrix.platform }}
-        if [ ${{ matrix.platform }} = "simulator" ]; then
-          bash ./utilities/run_unit_tests.sh -f ${{ matrix.firmware }} -p ${{ matrix.platform }} > test_results.txt || true
-          cat test_results.txt
-          if [ ! "$(tail -n 1 test_results.txt)" = "OK" ]; then exit 1; fi
+
+  run-unit-tests:
+    needs: check-format
+    if: github.event_name == 'pull_request'
+    strategy:
+      fail-fast: false
+      matrix:
+        firmware: [main, initial]
+        target: [release]
+        platform: [simulator]
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        submodules: recursive
+
+    - name: Restore build-tools
+      id: cache-build-tools
+      uses: actions/cache@v3
+      with:
+        path: build-tools
+        key: build-tools
+
+    - name: Install simulator dependencies
+      run: sudo apt update && sudo apt install libsdl2-dev --no-install-recommends -y
+
+    - name: Run tests
+      env:
+        CACHED: ${{ steps.cache-build-tools.outputs.cache-hit }}
+      run: |
+        if [ ! "${CACHED}" = "true" ]; then
+          bash ./utilities/ci/setup-build-tools.sh;
         fi
+        PATH="$PATH:$(pwd)/build-tools"
+        # Ignore any non-zero exits from simulator run using '|| true'
+        bash ./utilities/run_unit_tests.sh -f ${{ matrix.firmware }} -p ${{ matrix.platform }} > test_results.txt || true
+        cat test_results.txt
+        # Unity prints "OK" if all tests pass, "FAIL" if tests fail; return 1 to indicate failure
+        if [ ! "$(tail -n 1 test_results.txt)" = "OK" ]; then exit 1; fi
